import type { Signal, Strategy, Stats } from "./types";

const now = new Date();
const h = (hours: number) => new Date(now.getTime() - hours * 3600000).toISOString();

export const mockSignals: Signal[] = [
  {
    id: 1,
    asset: "BTC",
    direction: "long",
    confidence: 87,
    strategy_source: "whale_tracker",
    reasoning: "Large accumulation detected on-chain — whale wallets added 2,400 BTC in the last 4 hours. Historically bullish within 24h.",
    timestamp: h(0.5),
    outcome: "pending",
    entry_price: 84250,
    target_price: 87500,
    stop_loss: 82800,
  },
  {
    id: 2,
    asset: "ETH",
    direction: "long",
    confidence: 79,
    strategy_source: "sentiment_pulse",
    reasoning: "Social sentiment flipped strongly positive. Fear & Greed Index rose from 42 to 68 in 6 hours. ETH historically rallies 3-5% in this condition.",
    timestamp: h(1.2),
    outcome: "pending",
    entry_price: 3180,
    target_price: 3350,
    stop_loss: 3090,
  },
  {
    id: 3,
    asset: "SOL",
    direction: "short",
    confidence: 72,
    strategy_source: "liquidation_cascade",
    reasoning: "Massive long liquidation cluster at $168. If price dips below $172, expect cascade liquidation event driving price to $160 range.",
    timestamp: h(2),
    outcome: "pending",
    entry_price: 174,
    target_price: 160,
    stop_loss: 180,
  },
  {
    id: 4,
    asset: "BTC",
    direction: "long",
    confidence: 91,
    strategy_source: "funding_rate_arb",
    reasoning: "Funding rate deeply negative (-0.03%) across major exchanges. Short squeeze conditions forming with 3.2B in shorts at risk.",
    timestamp: h(3),
    outcome: "hit",
    entry_price: 82100,
    target_price: 85000,
    stop_loss: 80500,
  },
  {
    id: 5,
    asset: "DOGE",
    direction: "long",
    confidence: 65,
    strategy_source: "sentiment_pulse",
    reasoning: "Elon Musk tweeted a Shiba image. Historical pattern shows 8-15% DOGE pump within 2 hours of similar tweets.",
    timestamp: h(5),
    outcome: "hit",
    entry_price: 0.182,
    target_price: 0.21,
    stop_loss: 0.17,
  },
  {
    id: 6,
    asset: "ETH",
    direction: "short",
    confidence: 74,
    strategy_source: "whale_tracker",
    reasoning: "Major whale deposited 45,000 ETH to Binance. Large exchange inflows typically precede sell-offs within 12h.",
    timestamp: h(8),
    outcome: "miss",
    entry_price: 3250,
    target_price: 3080,
    stop_loss: 3320,
  },
  {
    id: 7,
    asset: "ARB",
    direction: "long",
    confidence: 68,
    strategy_source: "polymarket_edge",
    reasoning: "Polymarket probability for ARB ecosystem grant announcement jumped from 35% to 78%. Market hasn't priced this in yet.",
    timestamp: h(10),
    outcome: "hit",
    entry_price: 1.12,
    target_price: 1.35,
    stop_loss: 1.04,
  },
  {
    id: 8,
    asset: "BTC",
    direction: "short",
    confidence: 82,
    strategy_source: "liquidation_cascade",
    reasoning: "Long liquidation wall at $86,500. Price approaching resistance with declining volume — high probability of rejection and cascade.",
    timestamp: h(14),
    outcome: "hit",
    entry_price: 86200,
    target_price: 83500,
    stop_loss: 87500,
  },
  {
    id: 9,
    asset: "MATIC",
    direction: "long",
    confidence: 71,
    strategy_source: "funding_rate_arb",
    reasoning: "MATIC perpetual funding rate at -0.025% on Bybit. Historically, reversals follow within 6-12 hours at this level.",
    timestamp: h(18),
    outcome: "pending",
    entry_price: 0.74,
    target_price: 0.82,
    stop_loss: 0.70,
  },
  {
    id: 10,
    asset: "SOL",
    direction: "long",
    confidence: 85,
    strategy_source: "whale_tracker",
    reasoning: "Smart money wallets accumulated 890K SOL in past 8 hours. Combined with rising DEX volume, bullish setup confirmed.",
    timestamp: h(22),
    outcome: "hit",
    entry_price: 162,
    target_price: 178,
    stop_loss: 155,
  },
];

export const mockStrategies: Strategy[] = [
  {
    id: 1,
    name: "whale_tracker",
    description: "Tracks large wallet movements and exchange flows to detect accumulation/distribution patterns.",
    type: "on-chain",
    hit_rate: 0.73,
    total_signals: 142,
    status: "active",
  },
  {
    id: 2,
    name: "sentiment_pulse",
    description: "Aggregates social media sentiment, Fear & Greed Index, and news sentiment for directional signals.",
    type: "sentiment",
    hit_rate: 0.68,
    total_signals: 98,
    status: "active",
  },
  {
    id: 3,
    name: "liquidation_cascade",
    description: "Maps liquidation clusters across exchanges to predict cascade events and sharp price moves.",
    type: "derivatives",
    hit_rate: 0.71,
    total_signals: 67,
    status: "active",
  },
  {
    id: 4,
    name: "funding_rate_arb",
    description: "Monitors perpetual funding rates for extreme readings that historically precede mean reversion.",
    type: "derivatives",
    hit_rate: 0.76,
    total_signals: 53,
    status: "active",
  },
  {
    id: 5,
    name: "polymarket_edge",
    description: "Scans prediction market probability shifts for alpha on upcoming events and announcements.",
    type: "prediction-markets",
    hit_rate: 0.62,
    total_signals: 31,
    status: "active",
  },
  {
    id: 6,
    name: "volume_divergence",
    description: "Detects price-volume divergences across spot and derivatives markets for reversal signals.",
    type: "technical",
    hit_rate: 0.59,
    total_signals: 44,
    status: "inactive",
  },
  {
    id: 7,
    name: "memecoin_radar",
    description: "Early detection of memecoin momentum using social velocity, holder growth, and DEX volume spikes.",
    type: "social",
    hit_rate: 0.55,
    total_signals: 89,
    status: "active",
  },
];

export const mockStats: Stats = {
  total_signals: 524,
  accuracy: 0.698,
  assets_tracked: 12,
  active_strategies: 6,
  pending_signals: 14,
};
